name: Run tests

on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ls -a && cd ../ && ls -a && cd ../ && ls -a && mvn clean test
        working-directory: .
